### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by ranalytica** [jpkeller/aqsr#4]
Can you provide a vignette for this program, i.e.

- whole california dataset for pm2.5  
- dataset for a county
- dataset for a city

**Comment by kpkeller** [comment]
It's not a true vignette, but in https://github.com/jpkeller/aqsr/commit/56a47acb4d4cc422945fdcf89444a14ccacb3780 I added examples of these types of request to the readme.

**Comment by ranalytica** [comment]
Thanks. This is awesome
